#pragma once

/***********************************************************************************************/
enum {
    RESULT_OK = 0,
    RESULT_NOT_INITED_ERROR,
    RESULT_UNKNOWN_ERROR,
    RESULT_INTERNAL_ERROR,
    RESULT_BUSY,
    RESULT_NOT_INITED,
    RESULT_NODATA,
    RESULT_TIMEOUT,
    RESULT_THREAD_ERROR,
    RESULT_MEMORY_ERROR,
    RESULT_ARGUMENT_ERROR,
    RESULT_DATA_NOT_FOUND,
    RESULT_FULL_BUFFER_ERROR,

    /* FILE ERRORS */
    RESULT_CFG_DIR_CREATE_ERROR = 100,
    RESULT_FILE_NOT_FOUND,
    RESULT_SAVE_FILE_ERROR,
    RESULT_TIME_FUNC_ERROR,
    RESULT_FILE_OPEN_ERROR,
    RESULT_FILE_POLL_ERROR,

    /* SOCKET ERRORS */
    RESULT_SOCKET_CREATE_ERROR = 400,
    RESULT_SOCKET_CLOSE_ERROR,
    RESULT_SOCKET_CONNECT_ERROR,
    RESULT_SOCKET_BIND_ERROR,
    RESULT_SOCKET_ACCEPT_ERROR,
    RESULT_SOCKET_SEND_ERROR,
    RESULT_SOCKET_IOCTL_ERROR,
    RESULT_SOCKET_READ_ERROR,
    RESULT_SOCKET_IO_ERROR,
    RESULT_INET_PTON_ERROR,
    RESULT_OPEN_DEVICE_ERROR,
    RESULT_FCNTL_ERROR,
    RESULT_SOCKET_ERROR,
    RESULT_POLL_ERROR,

};
/***********************************************************************************************/
